
package soa.logging.ws.server;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Logging", targetNamespace = "http://ws.logging.soa/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Logging {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod(operationName = "Log")
    @RequestWrapper(localName = "Log", targetNamespace = "http://ws.logging.soa/", className = "soa.logging.ws.server.Log")
    @ResponseWrapper(localName = "LogResponse", targetNamespace = "http://ws.logging.soa/", className = "soa.logging.ws.server.LogResponse")
    public void log(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMessagesSN", targetNamespace = "http://ws.logging.soa/", className = "soa.logging.ws.server.GetMessagesSN")
    @ResponseWrapper(localName = "getMessagesSNResponse", targetNamespace = "http://ws.logging.soa/", className = "soa.logging.ws.server.GetMessagesSNResponse")
    public List<String> getMessagesSN(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMessagesSNT", targetNamespace = "http://ws.logging.soa/", className = "soa.logging.ws.server.GetMessagesSNT")
    @ResponseWrapper(localName = "getMessagesSNTResponse", targetNamespace = "http://ws.logging.soa/", className = "soa.logging.ws.server.GetMessagesSNTResponse")
    public List<String> getMessagesSNT(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3);

}
