
package soa.logging.ws.server;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "LoggingImplService", targetNamespace = "http://ws.logging.soa/", wsdlLocation = "http://localhost:8080/ws/logging?wsdl")
public class LoggingImplService
    extends Service
{

    private final static URL LOGGINGIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(soa.logging.ws.server.LoggingImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = soa.logging.ws.server.LoggingImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/ws/logging?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/ws/logging?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        LOGGINGIMPLSERVICE_WSDL_LOCATION = url;
    }

    public LoggingImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoggingImplService() {
        super(LOGGINGIMPLSERVICE_WSDL_LOCATION, new QName("http://ws.logging.soa/", "LoggingImplService"));
    }

    /**
     * 
     * @return
     *     returns Logging
     */
    @WebEndpoint(name = "LoggingImplPort")
    public Logging getLoggingImplPort() {
        return super.getPort(new QName("http://ws.logging.soa/", "LoggingImplPort"), Logging.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Logging
     */
    @WebEndpoint(name = "LoggingImplPort")
    public Logging getLoggingImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.logging.soa/", "LoggingImplPort"), Logging.class, features);
    }

}
